import crypto from 'node:crypto';

function cleanRepoName(name) {
  return String(name || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9-_]/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);
}

async function readJson(res) {
  return await res.json().catch(() => ({}));
}

async function githubFetch(path, token, options = {}) {
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'vanz-deployer',
      ...(options.headers || {})
    }
  });

  const data = await readJson(res);
  if (!res.ok) {
    const err = new Error(data.message || `GitHub error ${res.status}`);
    err.status = res.status;
    throw err;
  }
  return data;
}

async function uploadFileToVercel(fileName, content, token) {
  const buffer = Buffer.from(content, 'utf8');
  const sha = crypto.createHash('sha1').update(buffer).digest('hex');

  const uploadRes = await fetch('https://api.vercel.com/v2/now/files', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'text/plain; charset=utf-8',
      'x-vercel-digest': sha
    },
    body: content
  });

  if (!uploadRes.ok) {
    const data = await readJson(uploadRes);
    throw new Error(data.error?.message || data.message || `Gagal upload ${fileName} ke Vercel`);
  }

  return {
    file: fileName,
    sha,
    size: buffer.length
  };
}

async function createVercelDeployment(projectName, files, token) {
  const res = await fetch('https://api.vercel.com/v13/deployments', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      name: projectName,
      files,
      projectSettings: {
        framework: null,
        buildCommand: null,
        outputDirectory: null
      },
      target: 'production'
    })
  });

  const data = await readJson(res);
  if (!res.ok) {
    throw new Error(data.error?.message || data.message || `Vercel error ${res.status}`);
  }

  return data;
}

export default async function handler(req, res) {
  try {
    if (req.method !== 'POST') {
      return res.status(405).json({ message: 'Method tidak diizinkan' });
    }

    const githubToken = process.env.GITHUB_TOKEN;
    const vercelToken = process.env.VERCEL_TOKEN;

    if (!githubToken || !vercelToken) {
      return res.status(500).json({
        message: 'GITHUB_TOKEN atau VERCEL_TOKEN belum dipasang di Environment Variables.'
      });
    }

    const { repoName, htmlContent } = req.body || {};
    const safeRepoName = cleanRepoName(repoName);

    if (!safeRepoName) {
      return res.status(400).json({ message: 'Nama repo tidak valid.' });
    }

    if (!htmlContent || typeof htmlContent !== 'string') {
      return res.status(400).json({ message: 'Isi HTML kosong.' });
    }

    if (Buffer.byteLength(htmlContent, 'utf8') > 500 * 1024) {
      return res.status(400).json({ message: 'File terlalu besar. Maksimal 500KB.' });
    }

    const user = await githubFetch('/user', githubToken);
    const owner = user.login;

    const existingRepo = await fetch(`https://api.github.com/repos/${owner}/${safeRepoName}`, {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'User-Agent': 'vanz-deployer'
      }
    });

    if (existingRepo.status === 200) {
      return res.status(409).json({ message: 'Repo sudah ada. Pakai nama project lain.' });
    }

    if (existingRepo.status !== 404) {
      const data = await readJson(existingRepo);
      throw new Error(data.message || 'Gagal cek repo GitHub.');
    }

    const repo = await githubFetch('/user/repos', githubToken, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        name: safeRepoName,
        private: false,
        auto_init: true,
        description: 'Auto generated by Vanz Deployer'
      })
    });

    await githubFetch(`/repos/${owner}/${safeRepoName}/contents/index.html`, githubToken, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: 'Add index.html',
        content: Buffer.from(htmlContent, 'utf8').toString('base64'),
        branch: 'main'
      })
    });

    const vercelFiles = [await uploadFileToVercel('index.html', htmlContent, vercelToken)];
    const deployment = await createVercelDeployment(safeRepoName, vercelFiles, vercelToken);

    const deployUrl = deployment.url?.startsWith('http')
      ? deployment.url
      : `https://${deployment.url}`;

    return res.status(200).json({
      message: 'Deployment berhasil!',
      url: deployUrl,
      repo: repo.html_url
    });
  } catch (error) {
    console.error('Deploy error:', error);
    return res.status(500).json({ message: error.message || 'Server error.' });
  }
}
